# This is a basic workflow to help you get started with Actions

name: Create PR about current release into master

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [ sync ]
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "sync" ]
permissions: write-all
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/checkout@v4
      - name: Reset branch
        run: |
          git fetch --all

      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ github.token }}
          head: ${{ github.event.client_payload.target_branch }}
          base: master
          title: test





          
